name: Build, Test ,Deploy and Report the oficine code

on: push

jobs:
  build_with_docker:
      runs-on: ubuntu-latest
      steps:
        - name: Use the checkout feature
          uses: actions/checkout@v3
        - name: Setup nodde js
          uses: actions/setup-node@v4
        - name: Use cache for optimization
          uses: actions/cache@v4
          id: cache
          with:
            path: node_modules
            key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
        - name: Install Dependencies
          if: steps.cache.outputs-hit != 'true'
          run: npm ci
        - name: Build website
          run: npm run build
        - name: Test with local tests
          run: npm run test

